# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

require 'json'

# Se envia un objeto {}
vms_config = JSON.parse(ENV['vms_config'])

# Imprimir vms_config en la consola
#puts "vms_config in vagrant:"
#puts JSON.pretty_generate(vms_config)

Vagrant.configure("2") do |config|

  vms_config['vms'].each do |vm|

    config.vm.define vms_config['hostname'] do |subconfig|
      subconfig.vm.box = vms_config['box_image']
      subconfig.vm.hostname = vms_config['hostname']
      subconfig.vm.network :private_network, ip: vms_config['ip']

      # Configuración específica para VirtualBox
      if vm['provider'] == "virtualbox"
        subconfig.vm.provider "virtualbox" do |vb|
          vb.name = "#{vms_config['hostname']}_#{vms_config['ip']}"
          vb.memory = vms_config['memory']
          vb.cpus = vms_config['cpus']
        end
      elsif vms_config['provider'] == "hyperv"
        subconfig.vm.provider "hyperv" do |hv|
          hv.memory = vms_config['memory']
          hv.cpus = vms_config['cpus']
        end
      end


      configure_vm_script(subconfig, vms_config['script'])
      
      # if vm['provider'] == "hyperv"
      #   subconfig.vm.synced_folder vm['shared_folder_host'], vm['shared_folder_vm'], type: "smb", smb_username: vm['username'], smb_password: ENV['SMB_PASSWORD']
      # else
      #   subconfig.vm.synced_folder vm['shared_folder_host'], vm['shared_folder_vm'], create: true , owner: vm['username'], group: vm['username']
      # end

      if !vms_config['upfirsttime']
        subconfig.vm.synced_folder vms_config['shared_folder_host'], vms_config['shared_folder_vm'], create: true , owner: vms_config['username'], group: vms_config['username']
      end

    end    
  end
end


def configure_vm_script(config, script)
  config.vm.provision "shell", inline: <<-SHELL
    echo "Copiando y ejecutando el script...install_basic"
    mkdir -p scripts_to_provision
    cp /vagrant/scripts_to_provision/install_basic.sh /home/vagrant/scripts_to_provision/
    ls /home/vagrant/scripts_to_provision
    chmod +x /home/vagrant/scripts_to_provision/install_basic.sh
    /home/vagrant/scripts_to_provision/install_basic.sh
  SHELL
end